name       : allegro
version    : 5.2.6.0
release    : 12
source     :
    - https://github.com/liballeg/allegro5/releases/download/5.2.6.0/allegro-5.2.6.0.tar.gz : 5de8189ec051e1865f359654f86ec68e2a12a94edd00ad06d1106caa5ff27763
license    : Zlib
component  : programming
summary    : Allegro is a cross-platform library mainly aimed at video game and multimedia programming
description: |
    Allegro is a cross-platform library mainly aimed at video game and multimedia programming.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(physfs)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(xcursor)
    - pkgconfig(xpm)
    - pkgconfig(xxf86dga)
setup      : |
    %cmake \
        -DLIB_SUFFIX=64 \
        -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DWANT_PHYSFS=ON .
build      : |
    %make
install    : |
    %make_install
