name       : allegro
version    : 5.2.4
release    : 6
source     :
    - https://github.com/liballeg/allegro5/releases/download/5.2.4.0/allegro-5.2.4.0.tar.gz : 346163d456c5281c3b70271ecf525e1d7c754172aef4bab15803e012b12f2af1
license    : Zlib
component  : programming
summary    : Allegro is a cross-platform library mainly aimed at video game and multimedia programming
description: |
    Allegro is a cross-platform library mainly aimed at video game and multimedia programming.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(libturbojpeg)
    - pkgconfig(openal)
    - pkgconfig(physfs)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(xcursor)
    - pkgconfig(xpm)
    - pkgconfig(xxf86dga)
setup      : |
    %cmake \
        -DLIB_SUFFIX=64 \
        -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DWANT_PHYSFS=ON .
build      : |
    %make
install    : |
    %make_install
