name       : allegro
version    : 5.2.2
release    : 3
source     :
    - http://download.gna.org/allegro/allegro/5.2.2/allegro-5.2.2.tar.gz : e285b9e12a7b33488c0e7e139326903b9df10e8fa9adbfcfe2e1105b69ce94fc
license    : zlib
component  : programming
summary    : Allegro is a cross-platform library mainly aimed at video game and multimedia programming.
description: |
    Allegro is a cross-platform library mainly aimed at video game and multimedia programming.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(openal)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
    - pkgconfig(xcursor)
    - pkgconfig(xpm)
    - pkgconfig(xxf86dga)
    - libjpeg-turbo-devel
    - physfs-devel
setup      : |
    %cmake \
        -DLIB_SUFFIX=64 \
        -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DWANT_PHYSFS=ON .
build      : |
    %make
install    : |
    %make_install
